#import "@preview/fletcher:0.5.8": diagram, node, edge
#set page(width: auto, height: auto, margin: 10mm, fill: white)
#set text(font: "Linux Libertine", size: 10pt)

#diagram(cell-size: (40mm, 40mm), {
  node((-11, -1.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $b_1$)
#line(length: 100%)
#text(size: 9pt, `shape: (1, 1)`)
]), name: "0")
  node((-9, 0.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $"sum"(X_"train") W_1 + b_"shaper" b_1$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "1")
  node((-2, 0.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $ReLU(mean(ReLU("sum"(X_"train") W_1 + b_"shaper" b_1)) W_2 + b_"shaper" b_2) W_3 + b_"shaper" b_3$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "2")
  node((-10, 0.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $"sum"(X_"train") W_1$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "3")
  node((-6, -0.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $b_"shaper" b_2$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "4")
  node((-3, 0.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $b_"shaper" b_3$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "5")
  node((-6, 0.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $mean(ReLU("sum"(X_"train") W_1 + b_"shaper" b_1)) W_2$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "6")
  node((-4, -1.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $W_3$)
#line(length: 100%)
#text(size: 9pt, `shape: (1, 1)`)
]), name: "7")
  node((-11, 1.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $"sum"(X_"train")$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "8")
  node((-5, 0.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $mean(ReLU("sum"(X_"train") W_1 + b_"shaper" b_1)) W_2 + b_"shaper" b_2$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "9")
  node((-7, -1.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $b_2$)
#line(length: 100%)
#text(size: 9pt, `shape: (1, 1)`)
]), name: "10")
  node((-10, -0.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $b_"shaper" b_1$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "11")
  node((-7, 0.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $W_2$)
#line(length: 100%)
#text(size: 9pt, `shape: (1, 1)`)
]), name: "12")
  node((-7, 1.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $mean(ReLU("sum"(X_"train") W_1 + b_"shaper" b_1))$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "13")
  node((0, 0.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $sigmoid(ReLU(mean(ReLU("sum"(X_"train") W_1 + b_"shaper" b_1)) W_2 + b_"shaper" b_2) W_3 + b_"shaper" b_3) * scaleTen$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "14")
  node((-1, 0.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $sigmoid(ReLU(mean(ReLU("sum"(X_"train") W_1 + b_"shaper" b_1)) W_2 + b_"shaper" b_2) W_3 + b_"shaper" b_3)$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "15")
  node((-8, 0.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $ReLU("sum"(X_"train") W_1 + b_"shaper" b_1)$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "16")
  node((-4, 1.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $ReLU(mean(ReLU("sum"(X_"train") W_1 + b_"shaper" b_1)) W_2 + b_"shaper" b_2)$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "17")
  node((-4, -0.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $b_"shaper"$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "18")
  node((-11, 0.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $W_1$)
#line(length: 100%)
#text(size: 9pt, `shape: (1, 1)`)
]), name: "19")
  node((-4, 0.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $b_3$)
#line(length: 100%)
#text(size: 9pt, `shape: (1, 1)`)
]), name: "20")
  node((-3, -0.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $ReLU(mean(ReLU("sum"(X_"train") W_1 + b_"shaper" b_1)) W_2 + b_"shaper" b_2) W_3$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "21")
  node((-12, 0.0), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $X_"train"$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 11)`)
]), name: "22")
  node((-1, -0.5), block(stroke: 0.5pt, inset: 8pt, radius: 4pt, [
#align(center, $scaleTen$)
#line(length: 100%)
#text(size: 9pt, `shape: (959, 1)`)
]), name: "23")
  edge(label("6"), label("9"), "->", label: $$)
  edge(label("4"), label("9"), "->", label: $$)
  edge(label("0"), label("11"), "->", label: $$)
  edge(label("17"), label("21"), "->", label: $$)
  edge(label("16"), label("13"), "->", label: $$)
  edge(label("20"), label("5"), "->", label: $$)
  edge(label("11"), label("1"), "->", label: $$)
  edge(label("19"), label("3"), "->", label: $$)
  edge(label("1"), label("16"), "->", label: $$)
  edge(label("13"), label("6"), "->", label: $$)
  edge(label("8"), label("3"), "->", label: $$)
  edge(label("23"), label("14"), "->", label: $$)
  edge(label("9"), label("17"), "->", label: $$)
  edge(label("21"), label("2"), "->", label: $$)
  edge(label("10"), label("4"), "->", label: $$)
  edge(label("7"), label("21"), "->", label: $$)
  edge(label("5"), label("2"), "->", label: $$)
  edge(label("15"), label("14"), "->", label: $$)
  edge(label("18"), label("5"), "->", label: $$)
  edge(label("18"), label("11"), "->", label: $$)
  edge(label("18"), label("4"), "->", label: $$)
  edge(label("3"), label("1"), "->", label: $$)
  edge(label("2"), label("15"), "->", label: $$)
  edge(label("22"), label("8"), "->", label: $$)
  edge(label("12"), label("6"), "->", label: $$)
})